version: 0.2
env:
    variables:
        BALANCER_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/beethovenx-v2-optimism'
        MASTERCHEF_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/masterchefv2'
        RELIQUARY_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/reliquary'
        BLOCKS_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/fantom-blocks'
        BEETS_BAR_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/beets-bar'
        YEARN_VAULTS_ENDPOINT: 'https://d28fcsszptni1s.cloudfront.net/v1/chains/250/vaults/all'
        SUBGRAPH_ORIG: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/beets-bar'
        GAUGE_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-gauges-optimism'
        USER_SNAPSHOT_SUBGRPAH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/user-bpt-balances-fantom'
        VEBALLOCKS_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-gauges'
phases:
    install:
        commands:
            - yarn install
    build:
        commands:
            - yarn generate
            - yarn prisma generate
            - yarn prisma migrate deploy
            - yarn build
    post_build:
        commands:
            - echo Build completed on `date`
#      - echo Pushing to graph cdn
#      - npx graphcdn push
cache:
    paths:
        - 'node_modules/**/*'
artifacts:
    files:
        - node_modules/**/*
        - package.json
        - dist/**/*
        - Procfile
        - cron.yaml
        - .platform/**/*
        - .ebextensions/**/*
