extend type Query {
    sorGetSwapsNew(
        tokenIn: String!
        tokenOut: String!
        swapType: GqlSorSwapType!
        swapAmount: BigDecimal! #expected in raw amount
    ): GqlSorGetSwapsResponseNew!
    tradeResults: [GqlTradeResults]!
}

enum GqlSorSwapType {
    EXACT_IN
    EXACT_OUT
}

type GqlSorGetSwapsResponseNew {
    tokenIn: String!
    tokenOut: String!
    result: String!
}

type GqlTradeResults {
    id: String!
    timestamp: Int!
    chain: String!
    tokenIn: String!
    tokenOut: String!
    swapAmount: String!
    swapType: String!
    sorV1Result: String!
    sorV2Result: String!
    isSorV1: Boolean!
}
